In [33]:
import torch

In [34]:
X  = torch.tensor([ 4., 3.,  2.,  1. ])
Y  = torch.tensor(10.)
W1 = torch.tensor([[1., 2.,  3.,  4. ],[5.,6.,7.,8.]], requires_grad=True)
W2 = torch.tensor( [9., 10., 11.], requires_grad=True)
Z  = W1.mv(X)
Z

tensor([20., 60.], grad_fn=<MvBackward>)

In [35]:
# add bias
Z = torch.cat((Z, torch.tensor([1.])))
Z

tensor([20., 60.,  1.], grad_fn=<CatBackward>)

In [36]:
Y_ = Z.dot(W2)
Y_

tensor(791., grad_fn=<DotBackward>)

In [37]:
Loss = (Y - Y_) ** 2
Loss.backward(retain_graph=True)
W1.grad, W2.grad

(tensor([[56232., 42174., 28116., 14058.],
         [62480., 46860., 31240., 15620.]]), tensor([31240., 93720.,  1562.]))