In [137]:
import numpy  as np
import pandas as pd
import torch

In [138]:
# 自动梯度，叶子节点
x = torch.tensor([1.])# 需要float
y = x * torch.tensor([2])
y

tensor([2.])

In [139]:
x.requires_grad

False

In [140]:
y.requires_grad

False

In [141]:
y.requires_grad_(True)
y.requires_grad

True

In [142]:
z = y + 2
z

tensor([4.], grad_fn=<AddBackward0>)

In [143]:
z.requires_grad

True

In [144]:
a = y + z
a

tensor([6.], grad_fn=<AddBackward0>)

x = 1

y = 2 * x

z = y + 2

a = y + z

da/dy = 2

da/dz = 1

In [145]:
a.backward()
(y.grad, z.grad)

(tensor([2.]), None)

In [146]:
y.is_leaf # 叶子节点一般是神经网络的权重

True

In [147]:
z.is_leaf # 说明只保存叶子节点的梯度

False

In [148]:
a.backward() # 再次执行反向传播后梯度会叠加
(y.grad, z.grad)

(tensor([4.]), None)

In [149]:
# detach
z.detach_() # z的梯度不被跟踪，但仍在计算图里
a.backward()
y.grad

tensor([6.])

In [150]:
# detach
y.detach_()
a.backward()
y.grad

tensor([6.])